<a href="https://colab.research.google.com/github/pratik1707/ml_cycle_power_plant/blob/main/Combined%20Cycle%20Power%20Plant.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Artificial Neural Network

### Importing the libraries

In [23]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [24]:
tf.__version__

'2.17.1'

## Part 1 - Data Preprocessing

### Importing the dataset

In [25]:
dataset = pd.read_excel('Folds5x2_pp.xlsx')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

### Splitting the dataset into the Training set and Test set

In [34]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [35]:
print(X_train)
print(X_test)

[[  11.22   43.13 1017.24   80.9 ]
 [  13.67   54.3  1015.92   75.42]
 [  32.84   77.95 1014.68   45.8 ]
 ...
 [  16.81   38.52 1018.26   75.21]
 [  12.8    41.16 1022.43   86.19]
 [  32.32   67.9  1006.08   37.93]]
[[  28.66   77.95 1009.56   69.07]
 [  17.48   49.39 1021.51   84.53]
 [  14.86   43.14 1019.21   99.14]
 ...
 [  12.24   44.92 1023.74   88.21]
 [  27.28   47.93 1003.46   59.22]
 [  17.28   39.99 1007.09   74.25]]


## Part 2 - Building the ANN

### Initializing the ANN

In [28]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [29]:
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

### Adding the second hidden layer

In [30]:
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

### Adding the output layer

In [31]:
ann.add(tf.keras.layers.Dense(units = 1))

## Part 3 - Training the ANN

### Compiling the ANN

In [32]:
ann.compile(optimizer = 'adam', loss = 'mean_squared_error')

### Training the ANN model on the Training set

In [36]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 28118.4180
Epoch 2/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 212.7905
Epoch 3/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 196.8207
Epoch 4/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 181.9309
Epoch 5/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 164.0715
Epoch 6/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 143.0522
Epoch 7/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 125.0722
Epoch 8/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 102.7445
Epoch 9/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 88.2828
Epoch 10/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 71.4261
Epoch 11/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 59.0860
Epoch 12/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 48.8226
Epoch 13/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 40.5757
Epoch 14/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 37.2738
Epoch 15/100
240/24

### Predicting the results of the Test set

In [41]:
y_pred = ann.predict(X_test)

print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))


60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
[[432.16339111 431.23      ]
 [463.57183838 460.01      ]
 [467.0390625  461.14      ]
 ...
 [474.28948975 473.26      ]
 [440.41702271 438.        ]
 [459.73248291 463.28      ]]


In [40]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

ValueError: continuous is not supported